config/routes.rb
Rails.application.routes.draw do

  get 'friendships/index'

  get 'events/index'

  get 'events/new'

  get 'events/create'

  get 'events/edit'

  get 'events/show'

  get 'events/update'

  get 'events/destroy'

  root 'home#index'
  
  get 'home/index'
  
  resources :accounts, only: [:new, :create, :show]
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  
  get 'topping_prefs/:id/edit', to: 'people#edit', as: 'edit_topping_prefs'
  resources :people, only: [:update, :show]
  
  resources :events
  
  resources :friendships, only: [:index]
  

end

app/models/event.rb
class Event < ActiveRecord::Base
    validates :name, presence: true, length: { maximum: 40 }
    
    belongs_to :account
    
    has_many :invitations
    has_many :people, :through => :invitations
    
    has_many :pizzas
    
    def full_location_string
        str = ''
        
        if self.location_street_address
            str += self.location_street_address
            if self.location_city or self.location_state
                str += ', '
            end
        end
        
        if self.location_city
            str += self.location_city
            if self.location_state
                str += ', '
            end
        end
        
        str += self.location_state ? self.location_state : ''
        
        str += self.location_zip ? self.location_zip : ''
    end
    
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :is_authenticated?
    
    #Event
    # id: 1
    # account_id: 3
    # name: "The peace of the newly baked their black hands pro..."
    # location_street_address: nil
    # location_city: nil
    # location_state: nil
    # location_zip: nil
    # date: nil
    
    def index
        @events = (@current_account.events + @current_account.person.events).uniq
    end
    
    def show
        @event = Event.find params[:id]
        
        # nsfw:no
        # render json: reddit_query_data[0].attributes  # private instance method
        @reddit = reddit_query_data  # private instance method
        #render json: @reddit
    end
    
    def new
        @event = Event.new
    end
    #Event.first.attribute_names
    #["id", "account_id", "name", "location_street_address", "location_city", "location_state", "location_zip", "date", "created_at", "updated_at"]
    def create
        new_event = Event.create( params.require(:event).permit(Event.attribute_names - ["id", "account_id", "created_at", "updated_at"]) )
        
        if (new_event.persisted?)   # add self and friends to
            new_event.account = @current_account
            new_event.people << [@current_account.person] + @current_account.friends.map do |f| f.person end
            
            make_pizzas(new_event)
            new_event.save
            
            redirect_to event_path(new_event)
        end
    end
    
    def edit
        @event = Event.find params[:id]
        
        # render json: reddit_query_data[0].attributes  # private instance method
        @reddit = reddit_query_data  # private instance method
        #render json: @reddit
    end
    
    def update
        event = Event.find params[:id]
        make_pizzas(event)  # redo pizza formation
        event.save
        
        redirect_to event_path(event)
    end
    
    def destroy
        devent = Event.find(params[:id])
        devent_name = devent.name
        
        if !devent.pizzas.empty?   # clear out old pizzas
            devent.pizzas.each do |pizza| pizza.delete end
            devent.pizzas.clear
        end
        
        flash[:success] = "Event \"#{devent_name}\" deleted."
        
        devent.delete
        
        redirect_to events_path
    end
    
    private ##########################
    
    # data structure to help with formulating pizzas
    GroupToppings = Struct.new(:needed_toppings, :wanted_toppings, :mehed_toppings, :hated_toppings) do
        def initialize(*args)
            super(*args)
            
            self.needed_toppings = {}
            self.wanted_toppings = {}
            self.mehed_toppings = {}
            self.hated_toppings = {}
        end
    end
    
    def make_pizzas event
        #rconsole.log "Making pizzas"
        
        if !event.pizzas.empty?   # clear out old pizzas
            event.pizzas.each do |pizza| pizza.delete end
            event.pizzas.clear
            #rconsole.log "Cleared out old pizzas"
        end
        
        pizza_groups = [ {members: [], toppings: GroupToppings.new} ]
        #rconsole.log "Empty pizza_groups: #{pizza_groups}"
        
        event.people.each do |person|
            #rconsole.log "Evaluating pizza for #{person.name}"
            if pizza_groups[0][:members].empty? # first iteration of loop
                add_person_to_group(person, pizza_groups[0]) # initialize group with first person
                #rconsole.log "First person, initializing shit"
                next # next person
            end
            
            was_grouped = false
            
            pizza_groups.each do |group, i|
                
                #rconsole.log "#{group[:toppings][:needed_toppings].keys}, #{person.toppings_list_to_hash(:hated_toppings).keys}"
                
                if share_keys?(group[:toppings][:needed_toppings], person.toppings_list_to_hash(:hated_toppings)) or
                   share_keys?(group[:toppings][:hated_toppings], person.toppings_list_to_hash(:needed_toppings)) # incompatible preferences
                    #rconsole.log "incompatible preferences"
                    next
                else
                    #rconsole.log "adding to group #{i}"
                    add_person_to_group(person, group)
                    was_grouped = true
                end
            end
            
            if !was_grouped     #make a new group for this person
                #rconsole.log "Making new group for #{person.name}"
                new_group = { members: [], toppings: GroupToppings.new }
                add_person_to_group(person, new_group)
                
                pizza_groups << new_group
            end
        end
        
        #rconsole.log "Final pizza_groups: #{pizza_groups}"
        
        pizzas_toppings = pizza_groups.map do |group|
            group[:toppings][:needed_toppings].merge(group[:toppings][:wanted_toppings])
        end
        
        #rconsole.log "Pizza toppings: #{pizzas_toppings}"
        
        pizzas_toppings.each do |toppings|
            pizza = event.pizzas.create name: "Fancy Pizza Name Here"
            #pizza.toppings << toppings.keys
            pizza.toppings << Topping.find(toppings.keys)
            
            pizza.save
        end
    end
    
    def add_person_to_group person, group
        group_members = group[:members]
        group_toppings = group[:toppings]
        
        # add new person_id to group members
        group_members << person.id
        
        # merge each of the 4 topping lists
        group_toppings.members.each do |curr_list_name|
            # want group and person topping lists as hashes with topping_ids as keys, because merge
            
            #rconsole.log "list #{curr_list_name}"
            
            person_hash = person.toppings_list_to_hash(curr_list_name)
            #rconsole.log "Person hash #{person_hash}"
            group_hash = group_toppings[curr_list_name]
            #rconsole.log "Group hash #{group_hash}"
            
            # and now merge the lists
            group_hash = group_hash.merge(person_hash)
            #rconsole.log "Group hash after merge #{group_hash}"
            group[:toppings][curr_list_name] = group_hash
            #rconsole.log "group[:toppings][curr_list_name] #{group[:toppings][curr_list_name]}"
        end
        
        return group  # of unknown necessity
    end
    
    def share_keys? hash1, hash2
        hash1.keys.any? {|k| hash2.key?(k)}
    end
    
    def reddit_query_data
        sum_toppings = []
        
        @event.pizzas.each do |pizza|
            sum_toppings += pizza.toppings.pluck(:name)
        end
        
        sum_toppings.uniq!
        
        query_toppings = sum_toppings[0, 2] # confine number of toppings or reddit search won't find anything
        
        # rconsole.log query_toppings.join(' ')
        
        query = "pizza " + query_toppings.join(' ') + ' nsfw:no'
        
        RedditKit.search(query).results
        # return query
    end
end

app/helpers/events_helper.rb
module EventsHelper
    def us_states
    [
        ['State', nil, {class: 'disabled'}],
        ['Alabama', 'AL'],
        ['Alaska', 'AK'],
        ['Arizona', 'AZ'],
        ['Arkansas', 'AR'],
        ['California', 'CA'],
        ['Colorado', 'CO'],
        ['Connecticut', 'CT'],
        ['Delaware', 'DE'],
        ['District of Columbia', 'DC'],
        ['Florida', 'FL'],
        ['Georgia', 'GA'],
        ['Hawaii', 'HI'],
        ['Idaho', 'ID'],
        ['Illinois', 'IL'],
        ['Indiana', 'IN'],
        ['Iowa', 'IA'],
        ['Kansas', 'KS'],
        ['Kentucky', 'KY'],
        ['Louisiana', 'LA'],
        ['Maine', 'ME'],
        ['Maryland', 'MD'],
        ['Massachusetts', 'MA'],
        ['Michigan', 'MI'],
        ['Minnesota', 'MN'],
        ['Mississippi', 'MS'],
        ['Missouri', 'MO'],
        ['Montana', 'MT'],
        ['Nebraska', 'NE'],
        ['Nevada', 'NV'],
        ['New Hampshire', 'NH'],
        ['New Jersey', 'NJ'],
        ['New Mexico', 'NM'],
        ['New York', 'NY'],
        ['North Carolina', 'NC'],
        ['North Dakota', 'ND'],
        ['Ohio', 'OH'],
        ['Oklahoma', 'OK'],
        ['Oregon', 'OR'],
        ['Pennsylvania', 'PA'],
        ['Puerto Rico', 'PR'],
        ['Rhode Island', 'RI'],
        ['South Carolina', 'SC'],
        ['South Dakota', 'SD'],
        ['Tennessee', 'TN'],
        ['Texas', 'TX'],
        ['Utah', 'UT'],
        ['Vermont', 'VT'],
        ['Virginia', 'VA'],
        ['Washington', 'WA'],
        ['West Virginia', 'WV'],
        ['Wisconsin', 'WI'],
        ['Wyoming', 'WY']
    ]
    end
end

app/views/events/_pizzas.html.erb
<div class="rise red">
  <h5>Event Name</h5>
  <h3> <%= @event.name %> </h3>
  <% if !@event.people.empty? %>
    <h5>Participants</h5>
    <%= @event.people.map(&:name).join(", ") %>
  <% end %>
  <% if !@event.pizzas.empty? %>
    <h5>Pizzas</h5>
    <div class="well well-sm">
      <% @event.pizzas.each do |pizza| %>
        <h5><%= pizza.name %></h5>
        <ul>
          <% pizza.toppings.each do |topping| %>
            <li><%= topping.name %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  <% end %>
  <% if !@event.full_location_string.empty? %>
    <h5>At</h5>
    <p><%= @event.full_location_string %></p>
  <% end %>
  <% if @event.date %>
    <h5>On</h5>
    <p><%= @event.date %></p>
  <% end %>
  <% if @current_account.id == @event.account_id && action_name == 'edit' %>
    <%= form_for @event do |f| %>
      <div class="btn-group">
        <button class="btn btn-primary" type="submit">Recalculate Toppings</button>
        <%= link_to "Delete This Event", @event, method: :delete, class: 'btn btn-warning', data: {confirm: "Are you sure?"} %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/events/_reddit.html.erb
<div class="row">
<div class="rise black col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-8 col-lg-offset-2">
  <h3>And now some disharmony...</h3>
  <p>Enjoy the carefully crafted melody and distinctive counter-point of what Reddit has to say about your pizza.</p>
  
  <!--%= render plain: @reddit %-->
  
  <ol>
   <% if @reddit.respond_to? :each %>
    <% @reddit.each do |result| %>
     <% if result.attributes %>
      <% attributes = result.attributes %>
      <li>
        <%= link_to attributes[:title], attributes[:url] %> • <%= link_to "permalink", "http://www.reddit.com#{attributes[:permalink]}" %>
      </li>
     <% end %>
    <% end %>
   <% end %>
  </ol>
</div>
</div>

app/views/events/edit.html.erb
<div class="rise purple col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-8 col-lg-offset-2">

  <h2>Edit Event</h2>

  <%= render "pizzas" %>
  
</div>

<%= render "reddit" %>

app/views/events/index.html.erb
<div class="rise purple col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-8 col-lg-offset-2">

  <h2>Your Events</h2>
  
  <%= render "shared/flash" %>
  
  <% if !@events.empty? %>
    <% @events.each do |event| %>
      <div class="rise red">
        <h5>Event Name</h5>
        <h3>
          <% if @current_account.id == event.account_id %>
            <%= link_to event.name, edit_event_path(event) %>
          <% else %>
            <%= link_to event.name, event_path(event) %>
          <% end %>
        </h3>
        <% if !event.people.empty? %>
          <h5>Participants</h5>
          <%= event.people.map(&:name).join(", ") %>
        <% end %>
        <% if !event.pizzas.empty? %>
          <h5>Pizzas</h5>
          <%= event.pizzas.map(&:name).join(", ") %>
        <% end %>
        <% if !event.full_location_string.empty? %>
          <h5>At</h5>
          <p><%= event.full_location_string %></p>
        <% end %>
        <% if event.date %>
          <h5>On</h5>
          <p><%= event.date %></p>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <p>You are not part of any events.</p>
  <% end %>
  
  <%= link_to "New Event", new_event_path, class: 'btn btn-primary' %>
  
</div>

app/views/events/new.html.erb
<div class="rise purple col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-8 col-lg-offset-2">

  <h2>New Event</h2>
  
  <!-- ["id", "account_id", "name", "location_street_address", "location_city", "location_state", "location_zip", "date", "created_at", "updated_at"] -->
  <%= bootstrap_form_for @event do |f| %>
    <%= f.text_field :name, placeholder: "Event name", hide_label: true %>
    <%= f.text_field :location_street_address, placeholder: "Street address", class: 'input-sm', label: "Address (optional):" %>
    <div class="form-inline">
      <%= f.text_field :location_city, placeholder: "City", class: 'input-sm', hide_label: true %>
      <%= f.select :location_state, us_states, { hide_label: true }, { class: "input-sm col-xs-1" } %>
      <%= f.text_field :location_zip, placeholder: "Zip code", class: 'input-sm col-xs-3', hide_label: true %>
    </div>
    <div class="form-group form-inline input">
      <%= f.datetime_select :date, class: 'input-sm', label: "Date:" %>
    </div>
    <%= f.submit "Submit", class: "btn btn-primary pull-right" %>
  <% end %>
  
</div>

app/views/events/show.html.erb
<div class="rise purple col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-8 col-lg-offset-2">

  <h2>View Event</h2>

  <%= render "pizzas" %>
  
  <%= link_to "New Event", new_event_path, class: 'btn btn-primary' %>
  
</div>

<%= render "reddit" %>