config/routes.rb
Rails.application.routes.draw do

  get 'friendships/index'

  get 'events/index'

  get 'events/new'

  get 'events/create'

  get 'events/edit'

  get 'events/show'

  get 'events/update'

  get 'events/destroy'

  root 'home#index'
  
  get 'home/index'
  
  resources :accounts, only: [:new, :create, :show]
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  
  get 'topping_prefs/:id/edit', to: 'people#edit', as: 'edit_topping_prefs'
  resources :people, only: [:update, :show]
  
  resources :events
  
  resources :friendships, only: [:index]
  

end

app/models/account.rb
class Account < ActiveRecord::Base
    
    has_secure_password
    
    validates :email,    uniqueness: { case_sensitive: false, message: "email address in use" },
                         format: { with: /@/, message: "not a valid email address", on: :create },
                         presence: true
    
    validates :password, presence: true, on: :create
    
    belongs_to :person
    
    has_many :friendships, :foreign_key => "friender_id"
    has_many :friends, :through => :friendships
    
    has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
    has_many :frienders, :through => :inverse_friendships, :source => :friender
    
    has_many :events
    
    def self.authenticate email, password
        Account.find_by_email(email).try(:authenticate, password)
    end
end

app/models/event.rb
class Event < ActiveRecord::Base
    validates :name, presence: true, length: { maximum: 40 }
    
    belongs_to :account
    
    has_many :invitations
    has_many :people, :through => :invitations
    
    has_many :pizzas
    
    def full_location_string
        str = ''
        
        if self.location_street_address
            str += self.location_street_address
            if self.location_city or self.location_state
                str += ', '
            end
        end
        
        if self.location_city
            str += self.location_city
            if self.location_state
                str += ', '
            end
        end
        
        str += self.location_state ? self.location_state : ''
        
        str += self.location_zip ? self.location_zip : ''
    end
    
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
    belongs_to :friender, :class_name => "Account"
    belongs_to :friend, :class_name => "Account"
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :person
  belongs_to :event
end

app/models/people_hate_toppings.rb
class PeopleHateToppings < ActiveRecord::Base
    belongs_to :person
    belongs_to :topping
end

app/models/people_meh_toppings.rb
class PeopleMehToppings < ActiveRecord::Base
  belongs_to :person
  belongs_to :topping
end

app/models/people_need_toppings.rb
class PeopleNeedToppings < ActiveRecord::Base
  belongs_to :person
  belongs_to :topping
end

app/models/person.rb
class Person < ActiveRecord::Base
    validates :name, presence: true, #{ message: "must enter a name" },
                     length: { maximum: 15 }
    
    has_and_belongs_to_many :needed_toppings, :class_name => "Topping", :join_table => "people_need_toppings"
    has_and_belongs_to_many :wanted_toppings, :class_name => "Topping", :join_table => "people_want_toppings"
    has_and_belongs_to_many :mehed_toppings, :class_name => "Topping", :join_table => "people_meh_toppings"
    has_and_belongs_to_many :hated_toppings, :class_name => "Topping", :join_table => "people_hate_toppings"
    
    has_one :account
    
    has_many :invitations
    has_many :events, :through => :invitations
    
    
    def toppings_list_to_hash list_name
        person_arr = self.public_send(list_name).pluck(:id) # I understand this much
        person_hash = person_arr.reduce({}){|hash, id| hash[id] = true; hash } # but not quite this much
    end
    
end

app/models/pizza.rb
class Pizza < ActiveRecord::Base
    belongs_to :event
    
    has_and_belongs_to_many :toppings
end

app/models/pizzas_toppings.rb
class PizzasToppings < ActiveRecord::Base
    belongs_to :pizza
    belongs_to :topping
end

app/models/preferences_form.rb
# Pseudo(?)-model for collecting/filling in data in the topping preferences form.

class PreferencesForm
    include ActiveModel::Model  # a.k.a. ActiveMallard (walks, talks, and quacks like an ActiveRecord)
    
    def initialize(attributes={})
        super
        
        # add topping-based field names as instance variables to the PreferencesForm so I can serve it all up in a web form (like a boss)
        PreferencesForm.field_names.each do |var_name|
            instance_variable_set("@#{var_name}", :unlisted_toppings)
            
            # add accessors:
            eigenclass = class<<self; self; end # Magic from the internets, I have no idea what's going on here O_o
            eigenclass.class_eval do
                attr_accessor var_name
            end
        end
    end
    
    def self.field_names
        arr = []
        
        # loop through all toppings known to man and beast and postgres (mostly postgres)
        # and make 'topping'+(id) field names for each of them
        Topping.all.each do |topping|
            arr << "topping#{topping.id}"
        end
        
        return arr
    end
    
    def populate_from(person)
        person.needed_toppings.each do |topping|
            field_name = "@topping#{topping.id}".to_sym
            instance_variable_set(field_name, :needed_toppings)
        end
        
        person.wanted_toppings.each do |topping|
            field_name = "@topping#{topping.id}".to_sym
            instance_variable_set(field_name, :wanted_toppings)
        end
        
        person.mehed_toppings.each do |topping|
            field_name = "@topping#{topping.id}".to_sym
            instance_variable_set(field_name, :mehed_toppings)
        end
        
        person.hated_toppings.each do |topping|
            field_name = "@topping#{topping.id}".to_sym
            instance_variable_set(field_name, :hated_toppings)
        end
        
    end
    
end

app/models/topping.rb
class Topping < ActiveRecord::Base
    has_and_belongs_to_many :needers, :class_name => "Person", :join_table => "people_need_toppings"
    has_and_belongs_to_many :wanters, :class_name => "Person", :join_table => "people_want_toppings"
    has_and_belongs_to_many :mehers, :class_name => "Person", :join_table => "people_meh_toppings"
    has_and_belongs_to_many :haters, :class_name => "Person", :join_table => "people_hate_toppings"
    
    has_and_belongs_to_many :pizzas
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
    def us_states
    [
        ['State', nil, {class: 'disabled'}],
        ['Alabama', 'AL'],
        ['Alaska', 'AK'],
        ['Arizona', 'AZ'],
        ['Arkansas', 'AR'],
        ['California', 'CA'],
        ['Colorado', 'CO'],
        ['Connecticut', 'CT'],
        ['Delaware', 'DE'],
        ['District of Columbia', 'DC'],
        ['Florida', 'FL'],
        ['Georgia', 'GA'],
        ['Hawaii', 'HI'],
        ['Idaho', 'ID'],
        ['Illinois', 'IL'],
        ['Indiana', 'IN'],
        ['Iowa', 'IA'],
        ['Kansas', 'KS'],
        ['Kentucky', 'KY'],
        ['Louisiana', 'LA'],
        ['Maine', 'ME'],
        ['Maryland', 'MD'],
        ['Massachusetts', 'MA'],
        ['Michigan', 'MI'],
        ['Minnesota', 'MN'],
        ['Mississippi', 'MS'],
        ['Missouri', 'MO'],
        ['Montana', 'MT'],
        ['Nebraska', 'NE'],
        ['Nevada', 'NV'],
        ['New Hampshire', 'NH'],
        ['New Jersey', 'NJ'],
        ['New Mexico', 'NM'],
        ['New York', 'NY'],
        ['North Carolina', 'NC'],
        ['North Dakota', 'ND'],
        ['Ohio', 'OH'],
        ['Oklahoma', 'OK'],
        ['Oregon', 'OR'],
        ['Pennsylvania', 'PA'],
        ['Puerto Rico', 'PR'],
        ['Rhode Island', 'RI'],
        ['South Carolina', 'SC'],
        ['South Dakota', 'SD'],
        ['Tennessee', 'TN'],
        ['Texas', 'TX'],
        ['Utah', 'UT'],
        ['Vermont', 'VT'],
        ['Virginia', 'VA'],
        ['Washington', 'WA'],
        ['West Virginia', 'WV'],
        ['Wisconsin', 'WI'],
        ['Wyoming', 'WY']
    ]
    end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pizza'n Harmony</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <!-- Google fonts -->
  <link href='//fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
  <!-- <link href='http://fonts.googleapis.com/css?family=Quicksand:700' rel='stylesheet' type='text/css'> -->
  
  <!-- <link href='http://fonts.googleapis.com/css?family=Merriweather Sans' rel='stylesheet' type='text/css'> -->
  <link href='//fonts.googleapis.com/css?family=Arimo:400,400italic,700' rel='stylesheet' type='text/css'>
  
  <!-- Latest compiled and minified CSS & JS -->
  <!-- <link rel="stylesheet" media="screen" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"> -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <script src="//code.jquery.com/jquery.js"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  
  <!--%= include_gon %-->
  <%= javascript_include_tag(:rconsole) if Rails.env.development? %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
</head>
<body>

<div id="uber-container" class="container-fluid">
  <div class="row">
    <nav id="title" class="navbar navbar-default rise">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <% if flash[:login_out_msg] %>
          <%= content_tag :span, flash[:login_out_msg], class: "login-out-msg" %>
        <% end %>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#title-nav" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= root_path %>">
          <%= image_tag("logo_temp.png", alt: "Temp logo.") %> <span class="h1">Pizza'n Harmony</span>
        </a>
      </div>
      
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div id="title-nav" class="collapse navbar-collapse">
        <!-- <ul class="nav navbar-nav navbar-center">
          <li><a href="#">Sign up!</a></li>
        </ul> -->
        <ul class="nav navbar-nav navbar-right">
          <% if @current_account %>
            <li>
              <%= link_to @current_account.person.name, account_path(@current_account), class: "active-account-name" %> <br>
              <%= link_to "Sign out", logout_path, class: "account-sign-out" %>
            </li>                          <!-- edit_topping_pref_path(@current_account.person -->
            <li><%= link_to "My Toppings", edit_topping_prefs_path(@current_account.person) %></li>
            <li><%= link_to "Events", events_path %></li>
            <li><%= link_to "Friends", friendships_path %></li>
          <% else %>
            <li><%= link_to "Sign in", login_path, class: "account-sign-in" %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </nav>
    
    <section id="content">
      <%= yield %>
    </section>
    
  </div>
</div>

</body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |k,v| %>
  <div class="alert alert-<%= k %>">
    <%= v %>
  </div>
<% end %>